/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router. Run `pnpm dev` to regenerate.

import { Route as rootRoute } from "./routes/__root";
import { Route as ApiShareableImport } from "./routes/api/shareable.$";
import { Route as IndexImport } from "./routes/index";
import { Route as ProfileImport } from "./routes/profile";
import { Route as SharedTypeTokenImport } from "./routes/shared.$type.$token";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ProfileRoute = ProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRoute,
} as any);

const ApiShareableRoute = ApiShareableImport.update({
  id: "/api/shareable/$",
  path: "/api/shareable/$",
  getParentRoute: () => rootRoute,
} as any);

const SharedTypeTokenRoute = SharedTypeTokenImport.update({
  id: "/shared/$type/$token",
  path: "/shared/$type/$token",
  getParentRoute: () => rootRoute,
} as any);

rootRoute.addChildren([IndexRoute, ProfileRoute, ApiShareableRoute, SharedTypeTokenRoute]);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/profile": typeof ProfileRoute;
  "/api/shareable/$": typeof ApiShareableRoute;
  "/shared/$type/$token": typeof SharedTypeTokenRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/profile": typeof ProfileRoute;
  "/api/shareable/$": typeof ApiShareableRoute;
  "/shared/$type/$token": typeof SharedTypeTokenRoute;
}

const routeTree = rootRoute;

export { routeTree };
